import { Product } from "@/types/product";

const shopData: Product[] = [
  {
    title: "Rose Renewal Serum",
    category: "Skincare",
    description: "A cushion-light daily serum that leaves tired skin visibly brighter and deeply replenished.",
    benefits: ["Brightens dull-looking skin", "Supports a softer, smoother texture", "Delivers lasting hydration"],
    ingredients: ["Rosehip oil", "Bakuchiol", "Niacinamide", "Hyaluronic acid"],
    skinTypes: ["Normal", "Dry", "Combination"],
    concerns: ["Dullness", "Uneven tone", "Dehydration"],
    fragranceNotes: ["Fresh rose", "Green stem", "Soft musk"],
    routineStep: "treat",
    finish: "Radiant",
    size: "30 ml / 1 fl oz",
    labels: ["vegan", "cruelty-free", "clean"],
    reviews: 15,
    price: 89.0,
    discountedPrice: 64.0,
    id: 1,
    imgs: {
      thumbnails: [
        "/images/products/product-1-sm-1.png",
        "/images/products/product-1-sm-2.png",
      ],
      previews: [
        "/images/products/product-1-bg-1.png",
        "/images/products/product-1-bg-2.png",
      ],
    },
  },
  {
    title: "Velvet Skin Cleanser",
    category: "Skincare",
    description: "A creamy, non-foaming cleanser that melts away the day without leaving skin tight or stripped.",
    benefits: ["Gently removes makeup and SPF", "Protects the moisture barrier", "Leaves skin supple and calm"],
    ingredients: ["Oat lipid", "Squalane", "Calendula", "Glycerin"],
    skinTypes: ["Sensitive", "Dry", "Normal"],
    concerns: ["Sensitivity", "Dryness", "Redness"],
    routineStep: "cleanse",
    finish: "Comforting cream",
    size: "150 ml / 5 fl oz",
    labels: ["vegan", "cruelty-free", "dermatologist-tested"],
    reviews: 5,
    price: 42.0,
    discountedPrice: 31.0,
    id: 2,
    imgs: {
      thumbnails: [
        "/images/products/product-2-sm-1.png",
        "/images/products/product-2-sm-2.png",
      ],
      previews: [
        "/images/products/product-2-bg-1.png",
        "/images/products/product-2-bg-2.png",
      ],
    },
  },
  {
    title: "Cloud Dew Facial Mist",
    category: "Skincare",
    description: "A fine, cooling veil of botanical hydration for an instant reset wherever your day takes you.",
    benefits: ["Refreshes skin on contact", "Replenishes surface hydration", "Sets makeup with a dewy finish"],
    ingredients: ["Aloe vera", "Cucumber water", "Panthenol", "White tea"],
    skinTypes: ["All skin types"],
    concerns: ["Dehydration", "Dullness", "Heat-stressed skin"],
    routineStep: "hydrate",
    finish: "Dewy mist",
    size: "100 ml / 3.4 fl oz",
    labels: ["vegan", "cruelty-free", "clean"],
    reviews: 8,
    price: 38.0,
    discountedPrice: 28.0,
    id: 3,
    imgs: {
      thumbnails: [
        "/images/products/product-3-sm-1.png",
        "/images/products/product-3-sm-2.png",
      ],
      previews: [
        "/images/products/product-3-bg-1.png",
        "/images/products/product-3-bg-2.png",
      ],
    },
  },
  {
    title: "Soft Focus Foundation",
    category: "Complexion",
    description: "Buildable, breathable coverage with a soft-focus finish that still looks like your skin.",
    benefits: ["Evens the look of skin tone", "Blurs without looking heavy", "Wears comfortably all day"],
    ingredients: ["Jojoba esters", "Vitamin E", "Mineral pigments", "Glycerin"],
    skinTypes: ["Normal", "Combination", "Oily"],
    concerns: ["Uneven tone", "Visible pores", "Shine"],
    routineStep: "color",
    finish: "Soft matte",
    size: "30 ml / 1 fl oz",
    shades: [
      { name: "Porcelain", value: "#F3D8C6" },
      { name: "Petal", value: "#DCA68E" },
      { name: "Honey", value: "#B9764F" },
      { name: "Cocoa", value: "#704331" },
    ],
    labels: ["vegan", "cruelty-free", "clean"],
    reviews: 12,
    price: 54.0,
    discountedPrice: 41.0,
    id: 4,
    imgs: {
      thumbnails: [
        "/images/products/product-4-sm-1.png",
        "/images/products/product-4-sm-2.png",
      ],
      previews: [
        "/images/products/product-4-bg-1.png",
        "/images/products/product-4-bg-2.png",
      ],
    },
  },
  {
    title: "Cocoa Silk Body Butter",
    category: "Body Care",
    description: "A rich but quick-melting body cream that wraps dry skin in a silky cocoa-scented veil.",
    benefits: ["Softens rough, dry patches", "Seals in moisture", "Leaves skin touchably smooth"],
    ingredients: ["Cocoa butter", "Shea butter", "Marula oil", "Vitamin E"],
    skinTypes: ["Dry", "Very dry", "Normal"],
    concerns: ["Dryness", "Rough texture", "Loss of firmness"],
    fragranceNotes: ["Cacao", "Vanilla", "Amber"],
    routineStep: "body",
    finish: "Silken sheen",
    size: "200 ml / 6.7 fl oz",
    labels: ["vegan", "cruelty-free", "clean"],
    reviews: 7,
    price: 48.0,
    discountedPrice: 33.0,
    id: 5,
    imgs: {
      thumbnails: [
        "/images/products/product-5-sm-1.png",
        "/images/products/product-5-sm-2.png",
      ],
      previews: [
        "/images/products/product-5-bg-1.png",
        "/images/products/product-5-bg-2.png",
      ],
    },
  },
  {
    title: "Nourishing Hair Elixir",
    category: "Hair Care",
    description: "A weightless oil blend that smooths ends, softens strands, and gives hair a healthy-looking glow.",
    benefits: ["Smooths frizz and flyaways", "Adds luminous shine", "Nourishes dry ends"],
    ingredients: ["Argan oil", "Camellia oil", "Baobab oil", "Vitamin F"],
    concerns: ["Dryness", "Frizz", "Split ends"],
    fragranceNotes: ["Bergamot", "Jasmine", "Sandalwood"],
    routineStep: "hair",
    finish: "Glossy, weightless",
    size: "50 ml / 1.7 fl oz",
    labels: ["vegan", "cruelty-free"],
    reviews: 15,
    price: 57.0,
    discountedPrice: 39.0,
    id: 6,
    imgs: {
      thumbnails: [
        "/images/products/product-6-sm-1.png",
        "/images/products/product-6-sm-2.png",
      ],
      previews: [
        "/images/products/product-6-bg-1.png",
        "/images/products/product-6-bg-2.png",
      ],
    },
  },
  {
    title: "Hydra Lip Sleeping Mask",
    category: "Lip Care",
    description: "An overnight cushion for lips that wake up visibly smoother, softer, and comforted.",
    benefits: ["Intensely hydrates overnight", "Smooths the look of fine lines", "Comforts dry, chapped lips"],
    ingredients: ["Ceramides", "Mango butter", "Peptide complex", "Hyaluronic acid"],
    skinTypes: ["All skin types"],
    concerns: ["Dryness", "Chapping", "Texture"],
    routineStep: "lips",
    finish: "Glossy balm",
    size: "15 g / 0.5 oz",
    labels: ["vegan", "cruelty-free", "clean"],
    reviews: 18,
    price: 29.0,
    discountedPrice: 22.0,
    id: 7,
    imgs: {
      thumbnails: [
        "/images/products/product-7-sm-1.png",
        "/images/products/product-7-sm-2.png",
      ],
      previews: [
        "/images/products/product-7-bg-1.png",
        "/images/products/product-7-bg-2.png",
      ],
    },
  },
  {
    title: "Daily Mineral Sunscreen",
    category: "Sun Care",
    description: "A sheer mineral SPF that protects daily while leaving skin comfortable, fresh, and glow-ready.",
    benefits: ["Broad-spectrum SPF 30 protection", "Helps defend against dryness", "Layers under makeup"],
    ingredients: ["Non-nano zinc oxide", "Licorice root", "Squalane", "Green tea"],
    skinTypes: ["Sensitive", "Normal", "Combination"],
    concerns: ["Sun exposure", "Dullness", "Sensitivity"],
    routineStep: "protect",
    finish: "Natural glow",
    size: "50 ml / 1.7 fl oz",
    labels: ["vegan", "cruelty-free", "dermatologist-tested"],
    reviews: 10,
    price: 46.0,
    discountedPrice: 34.0,
    id: 8,
    imgs: {
      thumbnails: [
        "/images/products/product-8-sm-1.png",
        "/images/products/product-8-sm-2.png",
      ],
      previews: [
        "/images/products/product-8-bg-1.png",
        "/images/products/product-8-bg-2.png",
      ],
    },
  },
];

export default shopData;
